function Initialize-LabServer {
    <#
    .SYNOPSIS
        Guided setup that takes a lab server from zero to ready.
    .DESCRIPTION
        Interactive initialization workflow that:
        1. Validates prerequisites (PowerShell, modules, tools)
        2. Initializes the worklab context and vault
        3. Creates a starter worklab-config.yml if needed
        4. Sets up the Proxmox API token
        5. Inventories the hypervisor host (nodes, storage, bridges)
        6. Optionally builds foundation templates (VyOS, Ubuntu) via Packer

        After running this, the lab server is ready for New-Lab.
    .PARAMETER ProjectRoot
        Path to the worklab project root.
    .PARAMETER VaultName
        SecretManagement vault to use. Uses the default vault if not specified.
    .PARAMETER Credential
        Proxmox credentials for API token creation. Prompted if not supplied.
    .PARAMETER SkipTemplates
        Skip Packer template builds (just do inventory + credentials).
    .EXAMPLE
        Initialize-LabServer -ProjectRoot ~/Source/worklab
    .EXAMPLE
        Initialize-LabServer -ProjectRoot ~/Source/worklab -SkipTemplates
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory)]
        [ValidateScript({ Test-Path $_ -PathType Container })]
        [string]$ProjectRoot,

        [string]$VaultName,

        [PSCredential]$Credential,

        [switch]$SkipTemplates
    )

    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host " Worklab Server Initialization" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""

    # --- Step 1: Prerequisites ---
    Write-Host "Step 1: Checking prerequisites..." -ForegroundColor Cyan

    $prereqsFailed = $false

    if ($PSVersionTable.PSVersion.Major -lt 7) {
        Write-Host "  FAIL: PowerShell 7.0+ required" -ForegroundColor Red
        $prereqsFailed = $true
    }

    foreach ($mod in @('Microsoft.PowerShell.SecretManagement', 'powershell-yaml', 'PSHcl')) {
        if (-not (Get-Module -ListAvailable -Name $mod)) {
            Write-Host "  FAIL: Module $mod not installed" -ForegroundColor Red
            Write-Host "        Install-Module $mod -Scope CurrentUser" -ForegroundColor Yellow
            $prereqsFailed = $true
        }
    }

    foreach ($tool in @('packer', 'terraform')) {
        if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
            Write-Host "  FAIL: $tool not found on PATH" -ForegroundColor Red
            $prereqsFailed = $true
        }
    }

    if ($prereqsFailed) {
        throw "Prerequisites not met. Install the missing items above and try again."
    }
    Write-Host "  All prerequisites met." -ForegroundColor Green
    Write-Host ""

    # --- Step 2: Initialize context ---
    Write-Host "Step 2: Initializing worklab context..." -ForegroundColor Cyan

    $initParams = @{ ProjectRoot = $ProjectRoot }
    if ($VaultName) { $initParams.VaultName = $VaultName }
    Initialize-WorklabContext @initParams

    Write-Host "  Project root: $ProjectRoot" -ForegroundColor DarkGray
    Write-Host "  Vault: $($script:VaultName)" -ForegroundColor DarkGray
    Write-Host ""

    # --- Step 3: Config file ---
    Write-Host "Step 3: Checking worklab-config.yml..." -ForegroundColor Cyan

    $configPath = Join-Path $ProjectRoot "worklab-config.yml"
    if (-not (Test-Path $configPath)) {
        if ($PSCmdlet.ShouldProcess($configPath, "Create starter worklab-config.yml")) {
            $starterConfig = @"
# Worklab Configuration -- generated by Initialize-LabServer
hypervisor: proxmox
networking_mode: vyos

proxmox:
  api_url:
  api_token_id:
  node:
  storage_pool:
  iso_storage:
  lab_bridge:
  sdn_zone: worklab
  skip_cert_check: true

vyos:
  api_url:
  trunk_interface: eth1

terraform:
  role_defaults:
    dc:
      cores: 2
      memory: 4096
    member:
      cores: 2
      memory: 4096
    sql:
      cores: 4
      memory: 8192
      data_disk_size: 100
    workgroup:
      cores: 2
      memory: 4096
"@
            Set-Content -Path $configPath -Value $starterConfig -Encoding UTF8
            Write-Host "  Created starter config: $configPath" -ForegroundColor Green
        }
    }
    else {
        Write-Host "  Config exists: $configPath" -ForegroundColor DarkGray
    }

    $config = Get-WorklabConfig

    # Prompt for API URL if missing
    $apiUrl = Get-ConfigValue $config 'proxmox.api_url'
    if (-not $apiUrl) {
        Write-Host ""
        Write-Host "  Proxmox API URL is not set in config." -ForegroundColor Yellow
        $apiUrl = Read-Host "  Enter Proxmox API URL (e.g., https://pve.local:8006)"
        if ($apiUrl) {
            Set-WorklabConfigValue -Section proxmox -Key api_url -Value $apiUrl
        }
        else {
            throw "Proxmox API URL is required."
        }
    }
    Write-Host ""

    # --- Step 4: API Token ---
    Write-Host "Step 4: Setting up Proxmox API token..." -ForegroundColor Cyan

    $existingToken = Get-SecretInfo -Vault $script:VaultName -Name $script:ProxmoxTokenSecretName -ErrorAction SilentlyContinue
    if ($existingToken) {
        Write-Host "  API token already exists in vault." -ForegroundColor DarkGray
    }
    else {
        $tokenParams = @{}
        if ($Credential) { $tokenParams.Credential = $Credential }
        Initialize-ProxmoxToken @tokenParams
    }
    Write-Host ""

    # --- Step 5: Host inventory ---
    Write-Host "Step 5: Discovering host topology..." -ForegroundColor Cyan

    Connect-WorklabProxmox | Out-Null
    $inventory = Get-LabServerInventory -UpdateConfig
    Write-Host ""

    # --- Step 6: Templates (optional) ---
    if (-not $SkipTemplates) {
        Write-Host "Step 6: Foundation templates..." -ForegroundColor Cyan
        Write-Host "  Template builds (VyOS, Ubuntu) require ISOs and are handled by" -ForegroundColor DarkGray
        Write-Host "  the worklab consumer scripts (Build-Foundation.ps1)." -ForegroundColor DarkGray
        Write-Host "  Run Build-Foundation.ps1 to build the VyOS and Ubuntu templates." -ForegroundColor Yellow
        Write-Host ""
    }

    # --- Summary ---
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host " Initialization Complete" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Host: $($inventory.Nodes[0].Name) ($($inventory.Nodes[0].Cpu) CPUs, $($inventory.Nodes[0].Memory) GB RAM)" -ForegroundColor DarkGray
    Write-Host "Storage: $($inventory.StoragePools.Name -join ', ')" -ForegroundColor DarkGray
    Write-Host "Bridges: $($inventory.Bridges.Name -join ', ')" -ForegroundColor DarkGray
    Write-Host "VMs: $($inventory.ExistingVMs.Count) existing" -ForegroundColor DarkGray
    Write-Host "ISOs: $($inventory.IsoFiles.Count) available" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor DarkGray
    Write-Host "  1. Review worklab-config.yml" -ForegroundColor DarkGray
    Write-Host "  2. Build foundation: Build-Foundation.ps1 (VyOS + Ubuntu templates)" -ForegroundColor DarkGray
    Write-Host "  3. Build Windows templates: Build-Template.ps1" -ForegroundColor DarkGray
    Write-Host "  4. Create a lab: New-Lab -LabName lab-01 -VlanId 101 -IpCidr 10.101.0.0/24 -Domain lab01.internal" -ForegroundColor DarkGray
}
