function New-LabTerraform {
    <#
    .SYNOPSIS
        Generates Terraform files from an existing lab-config.yml.
    .DESCRIPTION
        Reads lab-config.yml (generated by New-LabConfig or edited manually),
        resolves template names to VM IDs, and generates main.tf, variables.tf,
        outputs.tf, and backend.tf.

        Use this to regenerate HCL after editing lab-config.yml (changing VM sizes,
        swapping templates, etc.) without re-specifying the original parameters.
    .PARAMETER LabName
        Lab name. Used to locate lab-config.yml in the conventional path.
    .PARAMETER LabConfigPath
        Override path to lab-config.yml. Defaults to terraform/labs/$LabName/lab-config.yml.
    .PARAMETER Force
        Overwrite existing .tf files without confirmation.
    .EXAMPLE
        New-LabTerraform -LabName lab-03
    .EXAMPLE
        New-LabTerraform -LabName lab-03 -LabConfigPath ./custom-config.yml
    .OUTPUTS
        System.String[] -- paths to the generated .tf files.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([string[]])]
    param (
        [Parameter(Mandatory)]
        [string]$LabName,

        [string]$LabConfigPath,

        [switch]$Force
    )

    if (-not $script:ProjectRoot) {
        throw "Project root not set. Call Initialize-WorklabContext first."
    }

    # Resolve lab config path
    if (-not $LabConfigPath) {
        $LabConfigPath = Join-Path $script:ProjectRoot "terraform" "labs" $LabName "lab-config.yml"
    }

    if (-not (Test-Path $LabConfigPath)) {
        throw "Lab config not found: $LabConfigPath. Run New-LabConfig first."
    }

    $labConfig = Get-Content $LabConfigPath -Raw | ConvertFrom-Yaml
    $labDir = Split-Path $LabConfigPath -Parent

    # Load worklab config for hypervisor/networking settings
    $config = Get-WorklabConfig
    $hypervisor = Get-ConfigValue $config 'hypervisor' 'proxmox'
    $networkingMode = Get-ConfigValue $config 'networking_mode' 'pfsense'

    # Extract network parameters from lab config
    $ipCidr = $labConfig.ip_cidr
    $gatewayIp = $labConfig.gateway_ip
    $vlanId = $labConfig.vlan_id
    $networkName = if ($labConfig.Contains('network_name')) { $labConfig.network_name } else { $LabName -replace '-', '' }

    $cidrParts = $ipCidr -split '/'
    $networkOctets = ($cidrParts[0]) -split '\.'
    $subnetBase = "$($networkOctets[0]).$($networkOctets[1]).$($networkOctets[2])"
    $subnetMask = $cidrParts[1]
    $dc1Ip = "$subnetBase.10"
    $dc2Ip = "$subnetBase.11"

    # Build the unified VM list from lab-config.yml
    $allVMs = [ordered]@{}

    # Infrastructure VMs
    if ($labConfig.Contains('infrastructure')) {
        foreach ($key in $labConfig.infrastructure.Keys) {
            $allVMs[$key] = $labConfig.infrastructure[$key]
        }
    }

    # Product VMs
    if ($labConfig.Contains('products')) {
        foreach ($prodKey in $labConfig.products.Keys) {
            $prod = $labConfig.products[$prodKey]
            if ($prod.Contains('vms')) {
                foreach ($vmKey in $prod.vms.Keys) {
                    $allVMs[$vmKey] = $prod.vms[$vmKey]
                }
            }
        }
    }

    if ($allVMs.Count -eq 0) {
        throw "No VMs defined in lab config: $LabConfigPath"
    }

    # Resolve all templates to VM IDs
    $registry = Get-TemplateRegistry
    $templateMap = @{}
    foreach ($vm in $allVMs.GetEnumerator()) {
        $tplName = $vm.Value.template
        if (-not $templateMap.Contains($tplName)) {
            $resolved = Resolve-TemplateVmId -TemplateName $tplName -Hypervisor $hypervisor -Registry $registry
            $templateMap[$tplName] = $resolved.VmId
        }
    }

    # Build products string for header comment
    $productsList = ""
    if ($labConfig.Contains('products')) {
        $productsList = ($labConfig.products.Keys | ForEach-Object {
            "$_`:$($labConfig.products[$_].version)"
        }) -join ', '
    }

    # Build vm_configurations entries
    $vmConfigEntries = @()
    foreach ($vm in $allVMs.GetEnumerator()) {
        $vmConfig = @{}
        foreach ($k in $vm.Value.Keys) { $vmConfig[$k] = $vm.Value[$k] }

        $entry = Get-VmConfigurationEntry `
            -VmName $vm.Key `
            -VmConfig $vmConfig `
            -LabName $LabName `
            -SubnetBase $subnetBase `
            -SubnetMask $subnetMask `
            -GatewayIp $gatewayIp `
            -Dc1Ip $dc1Ip `
            -Dc2Ip $dc2Ip `
            -TemplateVmId $templateMap[$vmConfig.template]
        $vmConfigEntries += $entry
    }

    $vmConfigurationsBlock = ($vmConfigEntries) -join ",`n"
    $providerVersions = Get-RequiredProvidersBlock -Hypervisor $hypervisor -NetworkingMode $networkingMode
    $providerBlocks = Get-ProviderConfigBlocks -Hypervisor $hypervisor -NetworkingMode $networkingMode
    $labNetworkArgs = Get-LabNetworkModuleBlock `
        -Hypervisor $hypervisor `
        -NetworkingMode $networkingMode `
        -LabName $LabName `
        -NetworkName $networkName `
        -VlanId $vlanId `
        -IpCidr $ipCidr `
        -GatewayIp $gatewayIp
    $vmModuleArgs = Get-VmModuleArgs -Hypervisor $hypervisor

    # Assemble main.tf
    $mainTf = @"
# Lab: $LabName -- Auto-generated by New-LabTerraform
# Hypervisor: $hypervisor | Networking: $networkingMode | Products: $productsList

terraform {
  required_version = ">= 1.5"

  required_providers {
$providerVersions
  }
}

locals {
  config     = yamldecode(file("`${path.root}/../../../worklab-config.yml"))
  lab_config = yamldecode(file("`${path.root}/lab-config.yml"))

  vm_configurations = [
$vmConfigurationsBlock
  ]
}

$providerBlocks

module "lab_network" {
$labNetworkArgs
}

module "vms" {
  source            = "../../modules/$hypervisor/vm"
  vm_configurations = local.vm_configurations
  network_id        = module.lab_network.network_id
$vmModuleArgs
  depends_on        = [module.lab_network]
}

"@

    $variablesHcl = Get-VariablesHcl -Hypervisor $hypervisor -NetworkingMode $networkingMode
    $backendHcl = Get-BackendHcl
    $outputsHcl = Get-OutputsHcl -LabName $LabName -VlanId $vlanId -IpCidr $ipCidr -VmNames @($allVMs.Keys)

    $generatedFiles = @()

    if ($PSCmdlet.ShouldProcess($labDir, "Generate Terraform files for $LabName ($($allVMs.Count) VMs, $hypervisor/$networkingMode)")) {
        Write-HclFile -Hcl $variablesHcl -Path $labDir -FileName "variables.tf"
        $generatedFiles += Join-Path $labDir "variables.tf"

        Write-HclFile -Hcl $backendHcl -Path $labDir -FileName "backend.tf"
        $generatedFiles += Join-Path $labDir "backend.tf"

        Write-HclFile -Hcl $mainTf -Path $labDir -FileName "main.tf"
        $generatedFiles += Join-Path $labDir "main.tf"

        Write-HclFile -Hcl $outputsHcl -Path $labDir -FileName "outputs.tf"
        $generatedFiles += Join-Path $labDir "outputs.tf"

        Write-Host "  Generated $($generatedFiles.Count) Terraform files in $labDir ($($allVMs.Count) VMs)" -ForegroundColor Green
    }

    return $generatedFiles
}
